@baseUrl = http://localhost:8080
@email1 = usuario1@email.com
@email2 = usuario2@email.com
#CRIA UMA SENHA AQUI,MAS NAO ENVIA ELA NO COMMIT PRA NAO FICAR DANDO ALERT NO GITGUARDIAN
#@password =
#CRIA UMA SENHA AQUI, MAS NAO ENVIA ELA NO COMMIT PRA NAO FICAR DANDO ALERT NO GITGUARDIAN
#@password2 =

#---------------------------------------------------------------
# swagger docs

### arquivo json
GET{{baseUrl}}/api/v3/api-docs
Content-Type: application/json

### pagina html
GET{{baseUrl}}/api/swagger-ui/index.html
Content-Type: application/json

#---------------------------------------------------------------
### /teste (endpoint publico / healthcheck)

GET{{baseUrl}}/api/teste
Content-Type: application/json

###

#---------------------------------------------------------------
# /usuarios (endpoints publicos)

### cadastrar usuario1
POST {{baseUrl}}/api/usuarios/signup
Content-Type: application/json

{
  "nome": "Nicholas Wrong",
  "email": "{{email1}}",
  "senha": "{{password}}"
}

### cadastrar usuario2
POST {{baseUrl}}/api/usuarios/signup
Content-Type: application/json

{
  "nome": "Barack Obama",
  "email": "{{email2}}",
  "senha": "{{password}}"
}

### testar login usuario1 apos cadastro
POST {{baseUrl}}/api/usuarios/login
Content-Type: application/json

{
  "email": "{{email1}}",
  "senha": "{{password}}"
}

### testar login usuario2 apos cadastro
POST {{baseUrl}}/api/usuarios/login
Content-Type: application/json

{
  "email": "{{email2}}",
  "senha": "{{password}}"
}

###

#---------------------------------------------------------------
# /usuarios (endpoints protegidos)

### atualizar usuario existente
PUT {{baseUrl}}/api/usuarios/3
Authorization: Basic {{email1}} {{password}}
Content-Type: application/json

{
  "nome": "Nicholas Wright",
  "senha": "{{password2}}"
}

### deletar usuario existente
DELETE {{baseUrl}}/api/usuarios/3
Authorization: Basic {{email1}} {{password2}}

###

#---------------------------------------------------------------
# eventos (endpoints protegidos)

### criar um novo evento com imagem
POST {{baseUrl}}/api/eventos
Authorization: Basic {{email2}} {{password}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="evento"
Content-Type: application/json

{
  "nome": "RAMADAN (COM IMAGEM)",
  "dataEvento": "2026-02-17T00:00:00",
  "localEvento": "Mecca, Saudi Arabia",
  "descricao": "the Holy Qur'an was sent down from heaven "
}
--boundary
Content-Disposition: form-data; name="imagem"; filename="sample1.png"
Content-Type: image/jpg

< ./sample1.png
--boundary-

### criar novo evento sem imagem
POST {{baseUrl}}/api/eventos
Authorization: Basic {{email2}} {{password}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="evento"  <-- CORRIJA ESTA LINHA
Content-Type: application/json

{
  "nome": "Roberto Carlos Especial (SEM IMAGEM)",
  "dataEvento": "2025-12-22T22:00:00",
  "localEvento": "Cruzeiro em Alto Mar",
  "descricao": "a jovem guarda era um programa de televisao."
}
--boundary--

### falha ao criar evento sem login senha
POST {{baseUrl}}/api/eventos
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="evento"
Content-Type: application/json

{
  "nome": "vai falhar",
  "dataEvento": "2033-12-10T10:00:00",
  "localEvento": "nada",
  "descricao": "deus esta morto"
}

### atualizar evento cadastrado
PUT {{baseUrl}}/api/eventos/1
Authorization: Basic {{email2}} {{password}}
Content-Type: application/json

{
  "nome": "RAMADÃ",
  "status": "CANCELADO"
}

### atualizar imagem de um evento cadastrado
PUT {{baseUrl}}/api/eventos/4/imagem
Authorization: Basic {{email2}} {{password}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="imagem"; filename="sample3.png"
Content-Type: image/png

< ./sample3.png
--boundary--

### deletar evento
DELETE {{baseUrl}}/api/eventos/4
Authorization: Basic {{email2}} {{password}}

###

#---------------------------------------------------------------
# eventos (endpoints publicos)

### buscar todos os eventos cadastrados
GET {{baseUrl}}/api/eventos

### buscar um evento unico
GET {{baseUrl}}/api/eventos/4


#---------------------------------------------------------------
# participantes (endpoints publicos)

### adicionar participante ao evento
POST {{baseUrl}}/api/eventos/5/participantes
Authorization: Basic {{email2}} {{password}}
Content-Type: application/json

{
  "nome": "LP",
  "email": "lpmaia13@gmail.com"
}

### adicionar participante ao evento
POST {{baseUrl}}/api/eventos/5/participantes
Authorization: Basic {{email2}} {{password}}
Content-Type: application/json

{
  "nome": "Nicolás Maduro",
  "email": "nicomad@venezualar.gov.br"
}

### tentar adicionar o mesmo partcipante
POST {{baseUrl}}/api/eventos/5/participantes
Authorization: Basic {{email2}} {{password}}
Content-Type: application/json

{
  "nome": "Nicolás Maduro",
  "email": "nicomad@venezualar.gov.br"
}

### remover participante
DELETE {{baseUrl}}/api/eventos/5/participantes/3
Authorization: Basic {{email2}} {{password}}

